org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.97
loader_version_range=[1,)

## Mod Properties
mod_id=ultimatecustomgear
mod_name=Ultimate Custom Gear
mod_license=MIT
mod_version=2.0.2
mod_group_id=arrivedbog593.ultimatecustomgear
author=ArrivedBog593, NadienDev
mod_description=Ultimate Custom Gear is a data-driven mod that allows server owners and modpack creators to add custom armor sets, weapons, tools, food items, blocks and fluids via simple JSON files. No coding required. Supports custom stats, held effects, set bonuses, per-piece armor values, layered damage resistances, 3D armor models via GeckoLib, custom textures, transparent armor, mob drops with Looting support, every vanilla recipe type plus passthrough recipes for other mods, tag integration and tag patching, distributable content packs, and multiplayer content verification.
displayURL=https://github.com/ArrivedBog593Dev/UltimateCustomGear

## Dependencies
jei_version=29.29.0.77
geckolib_version=5.5.2
curios_version=15.0.0
